# Generated by Django 6.0.6 on 2026-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighapp', '0004_vehicle_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='next_of_kin_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='farmer',
            name='next_of_kin_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='farmer',
            name='next_of_kin_relationship',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('weight_entry', 'Weight Entry'), ('farmer_created', 'Farmer Created'), ('farmer_updated', 'Farmer Updated'), ('vehicle_created', 'Vehicle Created'), ('report_viewed', 'Report Viewed'), ('receipt_printed', 'Receipt Printed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tractorallocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
