# Generated by Django 6.0.6 on 2026-07-25 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighapp', '0005_farmer_next_of_kin_name_farmer_next_of_kin_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingtransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('weight_entry', 'Weight Entry'), ('farmer_created', 'Farmer Created'), ('farmer_updated', 'Farmer Updated'), ('driver_created', 'Driver Created'), ('driver_updated', 'Driver Updated'), ('payment_marked', 'Driver Payment Marked'), ('vehicle_created', 'Vehicle Created'), ('report_viewed', 'Report Viewed'), ('receipt_printed', 'Receipt Printed')], max_length=20),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tractorallocation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='weighapp.driver'),
        ),
        migrations.AddField(
            model_name='weighingtransaction',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver who delivered this load, captured from the active allocation at gross weighing time', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='weighapp.driver'),
        ),
    ]
