# Generated by Django 6.0.6 on 2026-07-30 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighapp', '0008_user_must_reset_password_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('notification_type', models.CharField(choices=[('gross_weight', 'Gross Weight Recorded'), ('completion', 'Weighing Complete'), ('allocation', 'Tractor Allocated')], max_length=20)),
                ('recipient', models.CharField(help_text='Phone number or email address the message was sent to', max_length=150)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allocation', models.ForeignKey(blank=True, help_text='Set for tractor-allocation notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='weighapp.tractorallocation')),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='weighapp.farmer')),
                ('transaction', models.ForeignKey(blank=True, help_text='Set for gross-weight and completion notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='weighapp.weighingtransaction')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]