# Generated by Django 6.0.6 on 2026-08-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighapp', '0009_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('weight_entry', 'Weight Entry'), ('farmer_created', 'Farmer Created'), ('farmer_updated', 'Farmer Updated'), ('driver_created', 'Driver Created'), ('driver_updated', 'Driver Updated'), ('payment_marked', 'Driver Payment Marked'), ('password_self_reset', 'User Completed Mandatory Password Reset'), ('vehicle_created', 'Vehicle Created'), ('report_viewed', 'Report Viewed'), ('receipt_printed', 'Receipt Printed'), ('user_created', 'User Created'), ('password_reset_by_admin', 'Password Reset by Admin'), ('audit_log_viewed', 'Audit Log Viewed')], max_length=30),
        ),
    ]